#!/bin/bash

PROJECT_ROOT="$HOME/dev/lazysql"
SESSION_NAME="lazysql"
WINDOWS=(
  processes
  vim
  claude
  lazygit
  terminal
)

tmux has-session -t $SESSION_NAME 2>/dev/null

if [ $? != 0 ]; then
  for window in "${WINDOWS[@]}"; do
    if [ "$window" == "processes" ]; then
      tmux new-session -d -s $SESSION_NAME -n $window
    else
      tmux new-window -t $SESSION_NAME -n $window
    fi
  done
  tmux send-keys -t $SESSION_NAME:"${WINDOWS[0]}" "cd $PROJECT_ROOT" C-m
  tmux send-keys -t $SESSION_NAME:"${WINDOWS[1]}" "cd $PROJECT_ROOT && vim -S lazysql.vimsession" C-m
  tmux send-keys -t $SESSION_NAME:"${WINDOWS[2]}" "cd $PROJECT_ROOT && claude" C-m
  tmux send-keys -t $SESSION_NAME:"${WINDOWS[4]}" "cd $PROJECT_ROOT && lazygit" C-m
  tmux send-keys -t $SESSION_NAME:"${WINDOWS[5]}" "cd $PROJECT_ROOT" C-m

  tmux select-window -t $SESSION_NAME:"${WINDOWS[1]}"
fi

tmux attach-session -t $SESSION_NAME
