#!/bin/bash 

PROJECT_ROOT="$HOME/dev/sweaty_wallet"
SESSION_NAME="sweaty_wallet"

tmux has-session -t $SESSION_NAME 2>/dev/null

if [ $? != 0 ]; then
  declare -A windows
  windows[docker]="cd $PROJECT_ROOT && docker compose up --build"
  windows[lazygit]="cd $PROJECT_ROOT && lazygit"
  windows[main_app]="cd $PROJECT_ROOT/main_app && vim"
  windows[claude]="cd $PROJECT_ROOT && claude"
  windows[gemini]="cd $PROJECT_ROOT && gemini"
  windows[console]="cd $PROJECT_ROOT && ./docker_rails_console_login"
  windows[extension]="cd $PROJECT_ROOT/chrome_extension && vim"
  windows[terminal]="cd $PROJECT_ROOT"

  TABS=(
    lazygit
    main_app
    claude
    gemini
    console
    extension
    terminal
  )

  echo "Starting docker..."
  tmux new-session -d -s $SESSION_NAME -n "docker"
  tmux send-keys -t $SESSION_NAME:"docker" "${windows[docker]}" C-m

  for tab in "${TABS[@]}"; do
    tmux new-window -t $SESSION_NAME -n "$tab"
  done

  for key in "${!windows[@]}"; do
    if [ "$key" == "docker" ]; then
      continue
    fi
    tmux send-keys -t $SESSION_NAME:"$key" "${windows[$key]}" C-m
  done

  tmux select-window -t $SESSION_NAME:"main_app"
fi

tmux attach-session -t $SESSION_NAME


